### PR TITLE
Expose inner tdvp_iteration method. Simplify other wrappers.

### PR DESCRIPTION
**Pull request by emstoudenmire**
Summary of changes:

- Outermost (most user-facing) `tdvp` and `dmrg` methods specialize first on the Hamiltonian type, here just `MPO` versus `Vector{MPO}`, and let the user either pass a custom solver or else the default solver for each function is used.
- I moved the code for the solvers into their own functions `exponentiate_solver` and `eigsolve_solver` which return the actual solver functions
- The mid-level `tdvp` and `dmrg` functions (which can take any H, including the case of H being a ProjectedMPO etc.) call `_tdvp_compute_sweeps` to handle the logic of turning the total time plus a time_step into a call to `tdvp_iteration` doing multiple sweeps if the time_step is less than the total time. Here an alternative could be to call `tdvp_iteration` in a for loop, asking for one sweep at a time. A tricky thing about that is where to update the observer?
- Finally, `tdvp_iteration` differs from all of the above methods by applying a `time_step` amount of time evolution per sweep, versus the others where the interface guarantees that the total amount of time will be evolved (well as long as you let the number of sweeps be determined automatically... I'm realizing there's an issue if you pass a sweeps object with nsweeps > 1)

### CODE REVIEW

**Comment by mtfishman** [comment]
The more I've thought about this, the more I think we should be more strict about what `tdvp_iteration` means, and only have that involve one sweep. So the design I would imagine is the following:
```julia
function tdvp_iteration(solver, PH, time_step, psi; maxdim::Int, cutoff::Float64, [the rest of the keyword arguments needed for a single sweep])
  # One sweep of TDVP, so all of the code within `for sw in 1:nsweep(sweeps) [...] end`
  return PH, psi
end

function tdvp(solver, PH, time_step, psi, sweeps; kwargs...)
   for sw in 1:nsweep(sweeps)
     maxdim_sw = maxdim(sweeps, sw)
     cutoff_sw = cutoff(sweeps, sw)
     [...]
     PH, psi = tdvp_iteration(solver, PH, time_step, psi; maxdim=maxdim_sw, cutoff=cutoff_sw, kwargs...)
end
```
Then, we can see view this as a way for people to circumvent the `Sweeps` object and define their own set of sweeps. Does that make sense?

**Comment by emstoudenmire** [comment]
I agree this is a good direction to take it. It keeps both us and users from having trouble reasoning about what `tdvp_iteration` really does and is really for. It could help a lot, too, with the tricky issue of how observers will behave within these various functions.

Observer objects are sort of a lingering issue here, specifically in terms of knowing what sweep they are on. But I gather that Observers.jl uses `push!` internally already to get around this issue of having a special concept of "sweeps" or a special variable name like "sweep" it would look for?

**Comment by mtfishman** [comment]
Yes, deep down underneath, `Observers` is just calling `push!` on each `Vector` of results, where there is one `Vector` of results for each function that is passed into the `Observer`. So in the end, it would be a choice of whether you call `update!(::Observer, ...)` on every site or every sweep (or once every other sweep, or whatever). So I think that would be handled like the `outputlevel`, where you would have a keyword argument specifying at what level the `Observer` would get updated.

Alternatively, it could be handled at the `Observer` level, where the `Observer` functions could accept the sweep number and bond/site number and decide whether or not to do a measurement (I think the convention was that if the `Observer` function returns `nothing` than `update!` does nothing, but I would have to check).

**Comment by mtfishman** [comment]
Is there still some design choices with the time step/total time/nsweeps interface?

Maybe we can take some inspiration from the `range` function for how to deal with the interface: https://docs.julialang.org/en/v1/base/math/#Base.range, i.e. allow people to input a variety of options that minimally determine what is needed to figure out `t`, `time_step`, and `nsweeps`.

There could be a few options:
```julia
# `nsweeps` is determined automatically as `t / time_step`, but `t` and `time_step` must be commensurate
tdvp(H, psi0, t; time_step)

# `t` is determined from `nsweeps * time_step`
tdvp(H, psi0; nsweeps, time_step)

# `time_step` is determined automatically from `t / nsweeps`
tdvp(H, psi0, t; nsweeps)

# The inputs would need to satisfy `t == nsweeps * time_step` or else there will be an error
tdvp(H, psi0, t; nsweeps, time_step)

# Maybe this assumes `nsweeps = 1` and `time_step = t`?
tdvp(H, psi0, t)
```
I'm not sure what the current design is, does that match the current design? I think oftentimes people will want to measure at regular known intervals and therefore specify `time_step` and either `nsweeps` or `t`, whatever they think is most convenient.

Additionally, I think `tdvp_iteration` should only accept `t`, where implicitly `nsweeps = 1` and `time_step = t`:
```julia
tdvp_iteration(H, psi0, t)
```

Finally, I would vote for putting `t` at the beginning:
```julia
tdvp(t, H, psi0; time_step)
tdvp_iteration(t, H, psi0)
```
since to me it matches with the notation of `exp(t * H) * psi0`, but open to alternative views on that. We could match the `exponentiate` syntax and use:
```julia
tdvp(H, t, psi0; time_step)
tdvp_iteration(H, t, psi0)
```
Better yet we could just support both versions so we don't have to remember which one to use!

**Comment by emstoudenmire** [comment]
This is the direction I was also going with the interface, but I hadn't clearly delineated all of the cases you did so that's helpful. I agree this is the interface we want. (There is a very 'academic' case it wouldn't cover which is a kind of mode of using TDVP where there could be more than one sweep per time step, but I think the use cases for that are very limited and probably subspace expansions are the superior way to get accuracy and adaptivity.)

Regarding the order of t and H, I usually write time evolution as `exp(-i H t)` when working on paper so just mentioning that various conventions are in use with different people. But I don't have a strong opinion about the order of arguments here, and like the idea of just supporting more than one using types. (As a related example, I have been thinking we could support `MPO(sites,opsum)` in addition to `MPO(opsum,sites)` since I often have trouble remembering the correct order of arguments there and both make sense.)

Agreed that `tdvp_iteration` shouldn't accept any other time_step or t keyword arguments and really just enforce that it only evolves by an amount t. 

Do you think `tdvp_step` would be a better name? I went with iteration since it's a name used in ITensorInfiniteMPS but I go back and forth about it, no pun intended.

**Comment by emstoudenmire** [comment]
I updated this to now have the interface discussed above (except for the ordering of the arguments which I could still do and just forgot). But tests keep failing due to a number of ITensors.jl v0.3 / main branch features in use here. So might be worth waiting on that to be tagged versus making this code use backwards compatible features.

**Comment by b-kloss** [comment]
Hi,
sorry that I didn't comment on this issue earlier. Here's my take on the discussion of `tdvp_iteration` vs `tdvp_step`:

What is currently implemented as tdvp_iteration is a second-order timestep `dt` of the TDVP, where in forward and backward sweep we propagate by `dt/2`. In this sense `tdvp_step` is more appropriate. Maybe we can expose `tdvp_step` as a timestep with an `order` keyword, that would default to `order=2`, which is implemented already. Than `tdvp_step` would composed of some number of calls to `tdvp_iteration` (in the 2nd order case one forward and one backward). `tdvp_iteration` could determine itself whether it is supposed sweep right (forward) or left (backward) from the initial orthogonality center, but a `tdvp_iteration` is always a unidirectional sweep. This could lead to user-error if the orthogonality center is manipulated between iterations, but I don't think this is a huge concern and could be addressed when documenting the functionality?
The advantage of this design would be:
- easy implementation of higher-order integration schemes (which is quite an important practical consideration)
- easier interfacing with real-space parallel DMRG/TDVP (where after each unidirectional sweep of a partitioned MPS a call to some communication routine is required, which ideally would be implemented outside of `tdvp_iteration` at least (for example by providing a definition of `tdvp-step` that includes the parallel communication part))

Furthermore, regarding the higher-level interface, I think either `time_step` or `nsteps` should be non-keyword arguments, since there is not really a good way to provide a default. So
`tdvp(t, H, psi0, nsteps; nsteps_measure,order=2)`
or equivalently
`tdvp(t, H, psi0, time_step; time_step_measure,order=2)`.
which then would call `tdvp_step(time_step, H, psi0)` nsteps times and calculate observables at some commensurate interval given by nsteps.

**Comment by emstoudenmire** [comment]
These are really helpful observations. Agree with the point about there not being a good default time step and so requiring users to provide that. I had overlooked that because I was previously (in an earlier version of this code) just calling the tdvp function over and over again for each time step, so using t itself as the time step! 

Regarding the higher order TDVP schemes, what is a good reference for those and how they work? Also do you know if one can instead just pass a smaller "tol" (tolerance) parameter to the Krylov solver instead of doing a higher-order approach and get the same accuracy that way?

**Comment by mtfishman** [comment]
@b-kloss, thanks for pointing out that we should account for higher-order Trotterization schemes in our interface. Sounds like something we should consider in our interface that I wasn't considering properly.

Just to clarify, keyword arguments don't need to have defaults, and I wasn't assuming there was a default value for the `time_step` or `nsteps` in the interface I proposed above (unless they could be deduced from other inputs, for example deducing a `time_step` from `nsteps` and a total time `t`).

It would bother me if we ended up having 3 different functions (`tdvp`, `tdvp_step`, and `tdvp_iteration`) that all had similar functionality and interfaces, it makes me think that there is a more unified interface.

Maybe this can all be wrapped up into `tdvp_step`, where there is a lower-level interface that accepts a `time_step` and a set of bonds which get iterated over, for example something like:
```julia
n = length(psi0)
bonds=[(1, 2), (2, 3), [...], (n-1, n), (n-2, n-1), [...], (2, 3), (1, 2)])
tdvp_step(time_step, H, psi0, bonds)
```
Then, there could be a more convenient high-level interface like:
```julia
tdvp_step(time_step, H, psi0; order=2)
```
Base on the `order`, it generates a list of bonds corresponding to that Trotterization and calls the lower-level `tdvp_step` above.

Why don't we try to discuss this design in our meeting Wednesday, and if there's not enough time we can set up a followup meeting?

**Comment by b-kloss** [comment]
I implemented another version for the interface, using `tdvp` at all levels. There is still a bug somewhere, at least for 1-site evolution, but let me know what you think about the design.

**Comment by mtfishman** [comment]
Thanks Benedikt! Over all it looks good. I would have some suggestions with small things (for example I would put the `TDVPOrder` as the first argument of `tdvp`, and maybe get rid of `tdvp!`), but we don't need to do that in this PR. I think the priority is to have a starting point in the main branch that we can tweak and iterate on.

Another thing I might do is make the `TDVPOrder` type parametrized:
```julia
struct TDVPOrder{Order,Direction<:Base.Ordering} end
```
Then those can be dispatched on, for example this:
```julia
  if order==1
    sub_time_steps=[1.0,0.0]
    orderings=[direction, Base.ReverseOrdering(direction)]
  elseif order==2
    sub_time_steps=[1.0/2.0,1.0/2.0]
    orderings=[direction, Base.ReverseOrdering(direction)]
  elseif order==4
    s=1.0/(2.0-2.0^(1.0/3.0))
    sub_time_steps=[s/2.0,s/2.0,(1.0-2.0*s)/2.,(1.0-2.0*s)/2.0,s/2.0,s/2.0]
    orderings=repeat([direction, Base.ReverseOrdering(direction)],3)
  end
```
could be rewritten as a set of generic functions:
```julia
function time_steps_and_orderings(::TDVPOrder{1,Direction}) where {Direction}
    sub_time_steps=[1.0,0.0]
    orderings=[direction, Base.ReverseOrdering(Direction())]
    return sub_time_steps, orderings
end

[...]
```
So in the `tdvp` function you can just call:
```julia
sub_time_steps, orderings = time_steps_and_orderings(tdvp_order)
```
That would make it easier to define new time stepping schemes. But again, I think we should do that in a follow up PR.

**Comment by emstoudenmire** [comment]
I had fixed a bug earlier in the code (before this PR) that had to do with the if statements that check when to do a backwards step, depending on which half sweep one is on and which site or sites. So just mentioning it in case it gives some ideas about finding the bug.

**Pull request merged**
