### PR TITLE
Pass time of current time step as keyword argument to solver

### PR DESCRIPTION
**Pull request by mtfishman**
Also add example of TDVP with time dependent Hamiltonian.

### CODE REVIEW

**Comment by mtfishman** [comment]
@emstoudenmire @b-kloss this is pretty simple, the main thing to consider is the interface.

It keeps the same argument interface for a custom solver but passes a new keyword argument `time_step_start`:
```julia
function solver(H, time_step, psi; time_step_start)
  # Custom solver code here
end
```
`time_step_start` means that it is the time of the start of the current time step, open to suggestions about the name.

If you don't want to use the new keyword argument (for time independent Hamiltonians), you would need to define your solver like this:
```julia
function solver(H, time_step, psi; kwargs...)
  # Custom solver code here
end
```
There may be other cases you want to make use of the time to customize the arguments of the solver beyond just time dependent Hamiltonians (say you want to adjust the solver's tolerance, or even which solver you want to use).

Additionally, I expect there will be more and more keyword arguments we will want to pass to the solver since the solver in general will want information about the TDVP run. I think in general custom solvers will make use of some keyword arguments and not others, so it is not such an imposition to require adding `kwargs...` in the solver definition.

**Comment by emstoudenmire** [comment]
Glad to see this progressing. I'm hoping to work on the port of the basis expansion code soon. 

I'm missing some context about what time_step_start is for. What's an example of when that is needed? What does it do?

**Comment by b-kloss** [comment]
I imagine the use-case is a time-dependent Hamiltonian, where one makes the approximation that the Hamiltonian is time-independent for a single time-step of the propagator and updates the Hamiltonian before every timestep (but only to the past and present of the current orthogonality center (i.e. sites to the left of (and including) the orthogonality center, in a forward sweep). The advantage of updating the Hamiltonian like this instead of updating it everywhere at once is that the overhead of recomputing the Hamiltonian environment is avoided.
Maybe `tstart` is sufficient as keyword?

**Comment by mtfishman** [comment]
The application is for time-dependent Hamiltonians, where we put the time dependence in the solver and just pass the time independent part of the Hamiltonian.

Schematically it would be like this:
```julia
# Time dependent Hamiltonian
# H(t) = cos(omega * t) * H0

# Frequency
omega = 0.5

function solver(H0, time_step, psi; time_step_start)
  # Hamiltonian at the current time
  Ht = cos(omega * time_step_start) * H0

  # Apply the Hamiltonian at the current time to the current state.
  # We could use an ODE solver here, which would integrate from
  # `time_step_start` to `time_step_start + time_step`.
  return exponentiate(Ht, -im * time_step, psi)
end

# Time independent part of the Hamiltonian
H0 = heisenberg(n)
t = 10.0
tdvp(solver, H0, t; cutoff=1e-8)
```

There are a few advantages of this:

1. It enables a simple and flexible interface for dealing with time dependent Hamiltonians through the solver, instead of explicitly having to pass the time dependent Hamiltonian to `tdvp`. We could add support for directly passing time dependent Hamiltonians to `tdvp`, but doing it through the solver is minimally intrusive to the `tdvp` code itself and allows for more flexibility.
2. This approach makes it easy to try out other integrators like differential equation solvers that can account for the time dependence of the Hamiltonian _during_ the TDVP time step.
3. I'm not sure if I totally follow the example described by @b-kloss, but it sounds like this could add flexibility for other ways of running TDVP.

The idea behind the name `time_step_start` was to be specific that the time passed is the start of the current time step. I thought `tstart` or `time_start` may get confused with the global starting time of TDVP, which could be another values that is passed. For example, if you are restarting TDVP from a certain time, we may have a `time_start` that tracks the initial time, and you might want to know how long it has been since the initial time, which would be `time_step_start - time_start`.

**Comment by emstoudenmire** [comment]
Thanks for explaining & makes sense. 

Would it not be simpler to think of it as the current time (like the time evolved so far)? Then it could be called just `t` or a more explanatory name like `current_time` (or `t_so_far` or `t_evolved`). Thinking of it that way would also further disambiguate it from the starting time at the very beginning of the evolution.

**Comment by mtfishman** [comment]
In the latest I went with `current_time`, I think that one is clearest.

In the context of the overall TDVP scheme it is the current time of the evolution, but in the context of the solver it is the starting time of the particular time step you are performing. I was trying to come up with a name that made sense in the context of the solver instead of being too biased about where the time comes from, but I think those will essentially always be the same.

I also fixed a bug where I wasn't properly accounting for the times of the forward and backward evolution or the sub-time steps when computing the `current_time` that gets passed to the solver.

**Pull request merged**
